[manager]
prepend_keymap = [
{ on = ["<C-c>"], run = '''
    shell '~/copyfile.sh "$0"' --confirm
    ''', desc = "Copy file to system clipboard"},

{ on = ["c", "v"], run = '''
    shell '~/copyfile.sh "$0"' --confirm
    ''', desc = "Copy file to system clipboard"}
]
