# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ;hour
    replace: "{{currentHour}}"
    vars:
      - name: currentHour
        type: date
        params:
          format: "%H:%M"

  - trigger: ";date"
    replace: "{{currentDate}}"
    vars:
      - name: currentDate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ;time
    replace: "{{currentTimestamps}}"
    vars:
      - name: currentTimestamps
        type: date
        params:
          format: "%Y-%m-%d %H:%M"

  - trigger: ";bit"
    replace: "Bitbucket"

  - trigger: ";gcp"
    replace: "Google Cloud Platform"

  - trigger: ":pray:"
    replace: "🙏🏼"

  - trigger: ":peace:"
    replace: "✌🏼"

  - trigger: ":grimacing:"
    replace: "😬"

  - trigger: ";high"
    replace: "highlights::"

  - trigger: ";a"
    replace: "ã"
    propagate_case: true

  - trigger: ";o"
    replace: "õ"
    propagate_case: true

  - trigger: ";c"
    replace: "ç"
    propagate_case: true
